[package]
name = "hyprtheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive", "wrap_help", "env"] }
expanduser = "1.2.2"
pathdiff = "0.2.1"
toml = "0.5.10"
