[package]
name = "hyprtheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive", "wrap_help", "env"] }
colored = "2.0.0"
expanduser = "1.2.2"
fast_rsync = "0.1.4"
fs_extra = "1.2.0"
gitmodules = "0.1.0"
regex = "1.7.1"
reqwest = { version = "0.11.13", features = ["blocking"] }
toml = "0.5.10"
